### ISSUE TITLE
/nocache not working as permalink and with cloudflare

### ISSUE THREAD

**Issue by mahakala** [pcfreak30/wp-criticalcss#7]
hi,

is it possible to change the /nocache slug to an own slug? me for examle would need ?cache=no to exclude caching

thanks & best,
thomas

**Comment by pcfreak30** [comment]
Very sorry that I missed your issue. I never got notified of it.

Currently, this is done to get around situations where cache systems treat query strings special. internally it is just `?nocache`. In this way `nocache` pages are always "live" in that they get purged every time they are accessed so that they stay accurate for the criticalcss service.
